#!/usr/bin/env python3
"""AIGEN Daily Reports — autonomous publishing of protocol activity.

Every day at ~01:00 UTC:
  1. Composes a Markdown report of the previous 24h
  2. Saves to /home/luna/crypto-genesis/aigen/reports/{YYYY-MM-DD}.md
  3. Updates index.md with a link
  4. Reports become SEO-indexable URLs at /reports/{date}

Content per report:
  - Mission stats (created, resolved, voided, AIGEN paid)
  - New radar missions + token addresses covered
  - Winning safety reviews (top 5)
  - Treasury balance changes
  - Leaderboard movers (top 5 by ELO change)
  - Active subscribers
  - Notable on-chain events (USDC fees, AIGEN buybacks)

Output is Markdown that the scanner serves as HTML at /reports/{date}.md.

Modes:
  python3 reports_daemon.py once     # generate yesterday's report, exit
  python3 reports_daemon.py daemon   # check every hour, generate at ~01:00 UTC
  python3 reports_daemon.py date YYYY-MM-DD   # backfill specific date
"""
import argparse
import json
import logging
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("reports")

REPORTS_DIR = Path("/home/luna/crypto-genesis/aigen/reports")
REPORTS_DIR.mkdir(exist_ok=True)
MISSIONS_FILE = Path("/home/luna/crypto-genesis/aigen/missions.json")
LEDGER_FILE = Path("/home/luna/crypto-genesis/shield-rewards/ledger.json")
SUBSCRIBERS_FILE = Path("/home/luna/crypto-genesis/aigen/subscribers.json")


def _epoch_range_for_date(date_str: str) -> tuple[int, int]:
    """Return (start_epoch, end_epoch) for a UTC date YYYY-MM-DD."""
    d = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    start = int(d.timestamp())
    end = int((d + timedelta(days=1)).timestamp())
    return start, end


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def _short(addr: str) -> str:
    if not addr or len(addr) < 12:
        return addr or ""
    return f"{addr[:10]}…{addr[-4:]}"


def compose_report(date_str: str) -> str:
    """Build the Markdown report for a given UTC date."""
    start, end = _epoch_range_for_date(date_str)
    missions = _load_json(MISSIONS_FILE).get("missions", []) or []
    ledger = _load_json(LEDGER_FILE)
    subs = _load_json(SUBSCRIBERS_FILE).get("subscribers", []) or []

    # Filter to the date window
    created_today = [m for m in missions if start <= m.get("created_at", 0) < end]
    resolved_today = [m for m in missions
                      if m.get("status") == "resolved"
                      and start <= (m.get("resolution") or {}).get("resolved_at", 0) < end]
    voided_today = [m for m in missions
                    if m.get("status") == "voided"
                    and start <= (m.get("resolution") or {}).get("resolved_at", 0) < end]

    radar_today = [m for m in created_today if m.get("creator") == "aigen-radar"]
    autopilot_today = [m for m in created_today if m.get("creator") == "aigen-autopilot"]
    external_today = [m for m in created_today
                      if m.get("creator") not in ("aigen-radar", "aigen-autopilot",
                                                   "aigen-treasury", "mission-creator-001")]

    # AIGEN paid out today
    aigen_paid = sum(m.get("reward_aigen", 0) or 0
                     for m in resolved_today
                     if (m.get("reward") or {}).get("currency") == "AIGEN")
    usdc_paid_micros = sum((m.get("reward") or {}).get("amount", 0) or 0
                           for m in resolved_today
                           if (m.get("reward") or {}).get("currency") == "USDC")

    # Top 5 winning reviews (radar mission resolutions)
    radar_resolved = sorted(
        [m for m in resolved_today if m.get("creator") == "aigen-radar"],
        key=lambda x: (x.get("resolution") or {}).get("resolved_at", 0),
        reverse=True,
    )[:5]

    # Mover analysis (agents who got credits today)
    movers = []
    for aid, a in (ledger.get("agents", {}) or {}).items():
        today_credits = [c for c in (a.get("credits") or []) if start <= c.get("ts", 0) < end]
        if not today_credits:
            continue
        net = sum(c["amount"] for c in today_credits)
        if net > 0:
            movers.append((aid, net, len(today_credits)))
    movers.sort(key=lambda x: -x[1])
    top_movers = movers[:5]

    # Build the report
    lines = []
    lines.append(f"# AIGEN Daily Report — {date_str}")
    lines.append("")
    lines.append(f"_Auto-generated by `reports_daemon.py`. UTC day._")
    lines.append("")

    # Header stats
    lines.append("## Activity")
    lines.append("")
    lines.append(f"- Missions created: **{len(created_today)}** "
                 f"(radar: {len(radar_today)}, autopilot: {len(autopilot_today)}, external: {len(external_today)})")
    lines.append(f"- Missions resolved: **{len(resolved_today)}**")
    lines.append(f"- Missions voided: **{len(voided_today)}**")
    lines.append(f"- AIGEN paid out: **{aigen_paid}**")
    if usdc_paid_micros:
        lines.append(f"- USDC paid out: **${usdc_paid_micros/1e6:.4f}**")
    lines.append(f"- Active subscribers: {len(subs)}")
    lines.append("")

    # Radar coverage
    if radar_today:
        lines.append(f"## Radar coverage ({len(radar_today)} new tokens)")
        lines.append("")
        lines.append("| Mission | Chain | Token | Reward |")
        lines.append("|---------|-------|-------|--------|")
        for m in radar_today[:20]:
            mid = m.get("id", "?")
            title = m.get("title", "")
            # Extract chain + addr from title pattern "Safety review: BASE token 0x..."
            parts = title.replace("Safety review:", "").strip().split(" token ", 1)
            chain = parts[0].strip() if parts else "?"
            addr = parts[1].strip() if len(parts) > 1 else ""
            reward = m.get("reward_aigen", 0)
            lines.append(f"| [{mid}](/m/{mid}) | {chain} | `{addr}` | {reward} AIGEN |")
        lines.append("")

    # Top winning reviews
    if radar_resolved:
        lines.append(f"## Winning safety reviews")
        lines.append("")
        for m in radar_resolved:
            res = m.get("resolution") or {}
            winner_id = res.get("winner_submission_id")
            winner_sub = next((s for s in m.get("submissions", [])
                              if (s.get("id") or s.get("submission_id")) == winner_id), None)
            if not winner_sub:
                continue
            agent = winner_sub.get("submitter") or "?"
            verdict = (winner_sub.get("proof") or "").strip()[:300]
            lines.append(f"### [{m.get('title', '')}](/m/{m['id']})")
            lines.append(f"_Won by [{agent}](/agent/{agent})_  ")
            lines.append("")
            lines.append(f"> {verdict}")
            lines.append("")

    # External activity
    if external_today:
        lines.append("## External creators")
        lines.append("")
        for m in external_today[:10]:
            mid = m.get("id", "?")
            title = (m.get("title") or "")[:80]
            creator = m.get("creator", "?")
            reward = m.get("reward_aigen", 0)
            currency = (m.get("reward") or {}).get("currency", "AIGEN")
            amt = (m.get("reward") or {}).get("amount", reward)
            disp = f"{reward} AIGEN" if currency == "AIGEN" else f"{amt} {currency}"
            lines.append(f"- [{mid}](/m/{mid}) — _{title}_ by [{creator}](/agent/{creator}) ({disp})")
        lines.append("")

    # Top movers
    if top_movers:
        lines.append("## Top earners")
        lines.append("")
        lines.append("| Agent | AIGEN earned | Credits |")
        lines.append("|-------|--------------|---------|")
        for aid, net, count in top_movers:
            lines.append(f"| [{aid}](/agent/{aid}) | +{net} | {count} |")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"**Live**: [cryptogenesis.duckdns.org](https://cryptogenesis.duckdns.org) · ")
    lines.append(f"**RSS**: [/feed.xml](https://cryptogenesis.duckdns.org/feed.xml) · ")
    lines.append(f"**Safety reports**: [/feed/safety-reports.xml](https://cryptogenesis.duckdns.org/feed/safety-reports.xml)  ")
    lines.append("")
    lines.append(f"Browse all reports: [/reports/](https://cryptogenesis.duckdns.org/reports/)  ")
    lines.append(f"Source: [reports_daemon.py](https://github.com/Aigen-Protocol/aigen-protocol/blob/main/reports_daemon.py)")
    lines.append("")
    lines.append(f"_Generated at {int(time.time())} ({datetime.now(timezone.utc).isoformat()})._")

    return "\n".join(lines)


def write_report(date_str: str) -> Path:
    md = compose_report(date_str)
    path = REPORTS_DIR / f"{date_str}.md"
    path.write_text(md)
    log.info("wrote %s (%d bytes)", path, len(md))
    update_index()
    return path


def update_index():
    """Build /reports/index.md listing all daily reports."""
    reports = sorted([p for p in REPORTS_DIR.glob("*.md") if p.name != "index.md"], reverse=True)
    lines = ["# AIGEN Daily Reports", "",
             "Auto-generated archive of protocol activity. One report per UTC day.",
             "", f"_{len(reports)} reports archived._", ""]
    for p in reports[:365]:
        date_str = p.stem
        lines.append(f"- [{date_str}](/reports/{date_str}.md)")
    (REPORTS_DIR / "index.md").write_text("\n".join(lines))
    log.info("updated index.md (%d reports)", len(reports))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["once", "daemon", "date"], default="daemon", nargs="?")
    ap.add_argument("date", nargs="?", help="YYYY-MM-DD (only with mode=date)")
    args = ap.parse_args()

    if args.mode == "once":
        # Generate yesterday's report
        yesterday = (datetime.now(timezone.utc) - timedelta(days=1)).strftime("%Y-%m-%d")
        write_report(yesterday)
        return

    if args.mode == "date":
        if not args.date:
            print("Usage: reports_daemon.py date YYYY-MM-DD", file=sys.stderr)
            sys.exit(1)
        write_report(args.date)
        return

    # Daemon mode: check every hour, fire once after 01:00 UTC each day
    log.info("reports daemon starting (hourly check)")
    last_run_date = ""
    while True:
        now = datetime.now(timezone.utc)
        # If past 01:00 UTC and we haven't done today's "yesterday" report yet
        if now.hour >= 1:
            yesterday_str = (now - timedelta(days=1)).strftime("%Y-%m-%d")
            if last_run_date != yesterday_str:
                try:
                    p = write_report(yesterday_str)
                    last_run_date = yesterday_str
                    log.info("daily report shipped: %s", p)
                except Exception as e:
                    log.exception("report generation failed: %s", e)
        time.sleep(3600)


if __name__ == "__main__":
    main()
